# Local Variables:
# eval: (org-overview)
# End:

#+title: Info

* Tasks
** [l10n_in_Payroll] Fix the basic rule calculation condition in the Python code
**18.0**
PR:
https://github.com/odoo/enterprise/pull/35602

Task:
https://www.odoo.com/odoo/my-tasks/30621833

File:
l10n_in_hr_payroll/data/hr_rule_parameters_data.xml

Hint:
https://github.com/odoo/enterprise/pull/35602#discussion_r1119774480

Rule (Basic Salary, India: Regular Pay):
=result = max(payslip._rule_parameter('l10n_in_basic_value'), payslip.paid_amount * payslip._rule_parameter('l10n_in_basic_percent') * payslip._rule_parameter('l10n_in_basic_days'))=
Since payslip.paid_amout is 0, it thus does =max(700, 0)=

- empecher MONTHLY wage to be under the value
- et retirer max dans rule
- wage_hourly = hourly wage
- wage = monthly wage
- on master and not 18.0


** [Salary Config] Allow fields of salary config to be archived
**master**
archiver = mettre: active = fields.boolean(default=false) dans model
clean db = remove the fields you don't like (not a real dropdb _at all_)
-i hr_contract_salary


** [L10N_BE_Payroll] Changes since previous version
**master**
Chatter seems to be mail_message.py
OR mail_thread.py (hr_version inherits it)
Adding =tracking=True= in a python field makes the chatter send a message each time it is modified

in 18.3, the summary changes are in =enterprise/hr_contract_salary/controllers/main.py:849=
In the same file, the function is used. But I can't find a way to get the same logging as in the picture

The diff message is in send_diff_email:
=enterprise/hr_contract_salary/controllers/main.py:899=
To get it, you have to sign a new _offer_ in the Recruitment app.
I did it with Billy Kyle

=-m l10n_be_hr_payroll,hr_contract_salary=
Xavier (xbo) connait les trucks sur les tracking values (groups specifiques + perms, etc.)

WIP on branch *master-hr_contract_salary-add_diff_message_on_employee-mlef*


** [Employee] Migrate all "general" data to demo data
General data: =community/addons/hr/data/hr_data.xml=
Demo data: =community/addons/hr/data/hr_demo.xml=
Task is awaiting for some talks. Arthur knows a bit about it. He comes back from holidays on the 13 of aug
