#!/usr/bin/env bash

# Usage: this is a convenience script to quickly start and reload odoo.
# It was made to prevent tiresome, manual operations to reboot the containers.

set -eu

project_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
cd "$project_dir"

compose_file="$project_dir"/docker/docker-compose.yml

# Options that do not work in .odoorc
default_args="--dev=all --limit-time-real=0"

error() {
	error_message="
$0 usage:
	-m | --module <module_name>
		Select the module to update / install.
		It can also be a comma-separated module_name list.
	-d | --drop
		Drop the database to start on an empty session.
		This will automatically reinstall the module.
	-i | --install
		Installs the module in the database.
	-s | --stop
		Stop all containers
	-t | --test [-][tag][/module][:class][.method][[params]]
		Enables testing for filtered tests.
		The '-' specifies whether to include or to exclude matched tests.
		Example: -t :TestClass.test_func,/test_module,external
		It is also possible to provide parameters to a test method that supports
		them. Example: -t /web.test_js[mail]
	--odoo-help
		Show the help prompt from odoo-bin
	--debug
		Enables debugpy. May crash on live code change.
	--setup
		Sets up the whole project + dependencies
	--odoo-version
		Show the odoo version
	-h | --help
		Show this help prompt."
	[[ "$1" = "" ]] || echo "$1" 1>&2
	echo "$error_message" 1>&2
}

# default values
drop=0
install=0
help=0
stop=0
module=""
test=""
demo=0
odoo_help=0
odoo_version=0
enable_debug=0
setup=0
cmd="$default_args"

# parse script parameters
while [[ "$#" -gt 0 ]]; do
	case $1 in
	-m | --module)
		module="$2"
		shift
		;;
	-t | --test)
		test="$2"
		shift
		;;
	-d | --drop) drop=1 && install=1 ;;
	-i | --install) install=1 ;;
	-s | --stop) stop=1 ;;
	-D | --demo) demo=1 ;;
	--odoo-help) odoo_help=1 ;;
	--odoo-version) odoo_version=1 ;;
	--debug) enable_debug=1 ;;
	--setup) setup=1 ;;
	-h | --help) help=1 ;;
	*)
		error "Error: unknown parameter passed: \"$1\""
		exit 1
		;;
	esac
	shift
done

# show help prompt
if [[ $help = 1 ]]; then
	error ""
	exit 0
fi

# Setup the whole project
if [[ $setup = 1 ]]; then
	echo '"--setup" specified. Calling setup container...'
	docker compose -f "$compose_file" run --build setup
	exit 0
fi

check_possible_errors() {
	echo -e "\e[33m" # start yellow text
	cd "$project_dir/community" &&
		community_branch=$(git rev-parse --abbrev-ref HEAD)
	cd "$project_dir/enterprise" &&
		enterprise_branch=$(git rev-parse --abbrev-ref HEAD)
	cd "$project_dir"
	[[ "$community_branch" == "$enterprise_branch" ]] ||
		echo "Warning: community and enterprise branches differ.
	community_branch=$community_branch
	enterprise_branch=$enterprise_branch" 1>&2
	echo -e "\e[0m" # end yellow text
}

check_possible_errors

# just stop everything
if [[ $stop = 1 ]]; then
	echo "-s has been specified. Stopping all running containers."
	docker compose -f "$compose_file" down --remove-orphans && echo "Stopped all running containers."
	exit 0
fi

# user did not mention module name (-m | --module <module_name>)
if [[ "$module" = "" ]]; then
	echo "Warning: missing module (-m) parameter.
         No module will be updated / installed." 1>&2
else # seeing if installing (-i) or updating (-u) module
	if [[ $install = 1 ]]; then
		echo "\"$( ([[ $drop = 1 ]] && echo '--drop') || echo '--install')\"" \
			'has been specified. Adding "-i" to command'
		action="-i"
	else
		echo '"--install" has not been specified. Adding "-u" to command'
		action="-u"
	fi
	cmd="$cmd $action $module"
fi

if ! [[ "$test" = "" ]]; then
	echo '"-t" has been specified. Adding test arguments to cmd'
	cmd="$cmd --stop-after-init --log-level=info --test-enable --test-tags=$test"
	if [[ "$module" = "" ]]; then
		echo "Warning: no module has been set to be \
			tracked (-m) or installed (-i). Tests may not work." 1>&2
	fi
fi

if [[ $demo = 1 ]]; then
	echo "-D has been specified. Enabling demo data"
	cmd="$cmd --without-demo=False"
else
	echo "Demo data is disabled"
	cmd="$cmd --without-demo=True"
fi

echo "Shutting down everything"
docker compose -f "$compose_file" down --remove-orphans

echo "Starting db container..."
docker compose -f "$compose_file" up -d db

# Wait for database to be up
tries=1
while (! docker compose -f "$compose_file" ps | grep -qE "[^a-zA-Z](db|postgres)[^a-zA-Z].*?\sUp\s") && [ $tries -lt 5 ]; do
	sleep 0.5
	tries=$(("$tries" + 1))
	echo "Checking database availability ($tries)..."
done
if [ $tries = 5 ]; then
	echo "Error: could not start database" 1>&2
	exit 1
fi

if [[ $drop = 1 ]]; then
	echo '"--drop" has been specified. Dropping postgres database...'
	docker compose -f "$compose_file" exec db dropdb --user=odoo odoo || echo "Warning: failed to drop datatbase" 1>&2
fi

if [[ $odoo_version = 1 ]]; then
	echo '--odoo-version has been specified. Overriding parameters to --version'
	cmd="--version"
fi
if [[ $odoo_help = 1 ]]; then
	echo '--odoo-help has been specified. Overriding parameters to --help'
	cmd="--help"
fi

echo "Starting odoo container with \"$cmd\" parameters..."
docker compose -f "$compose_file" run --build -e "ENABLE_DEBUG=$enable_debug" --service-ports odoo $cmd
