[[config]]
name = "default"
odoo_path = "/home/martin/Projects/odoo/community"
addons_path = ["/home/martin/Projects/odoo/enterprise"]
python_path = "/home/martin/Projects/odoo/venv/bin/python" # check if correct
additional_stubs = ["/home/martin/Desktop/odoo-ls/typeshed/stubs"]


# in eglot-workspace-configuration, you can setup Odoo.selectedProfile to change profiles
