FROM phusion/baseimage:noble-1.0.2

ENV ODOO_DIR=/app

WORKDIR $ODOO_DIR

RUN apt-get update -y && apt-get install -y \
	git \
	python3 \
	python3-pip \
	python3-venv \
	python3-dev \
	libpq-dev \
	libldap2-dev \
	libsasl2-dev \
	gcc

# To allow git operations in odoo repos
RUN git config --global --add safe.directory "*"

COPY ./scripts/setup.bash ./setup.bash
ENTRYPOINT ["bash", "./setup.bash"]
