FROM phusion/baseimage:noble-1.0.2@sha256:b1b968db1eb391059048211e18df74062aa0777ffaecfd55f120ca34fdeb0630

ENV ODOO_DIR=/app

WORKDIR $ODOO_DIR

RUN apt-get update -y && apt-get install -y \
	git \
	python3 \
	python3-pip \
	python3-venv \
	python3-dev \
	libpq-dev \
	libldap2-dev \
	libsasl2-dev \
	gcc \
    npm

# To allow git operations in odoo repos
RUN git config --global --add safe.directory "*"

COPY ./scripts/enable-eslint.bash ./enable-eslint.bash
COPY ./scripts/setup.bash ./setup.bash
ENTRYPOINT ["bash", "./setup.bash"]
