FROM phusion/baseimage:noble-1.0.2

ENV ODOO_DIR=/app

WORKDIR $ODOO_DIR

RUN apt-get update -y && apt-get install -y \
	python3 \
	python3-pip \
	git

COPY ./scripts/setup.bash ./setup.bash
ENTRYPOINT ["bash", "./setup.bash"]
