name: odoo-dev

services:
  db:
    hostname: db
    image: postgres:latest
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: odoo
    ports:
      - "127.0.0.1:5432:5432"
    restart: on-failure:10
    healthcheck:
      test: pg_isready
      interval: 5s
      retries: 5
      start_period: 1s
      timeout: 5s
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
      - /var/run/postgresql:/var/run/postgresql

  odoo:
    network_mode: host # because debugpy uses ephemeral ports
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.odoo
    volumes:
      - ../enterprise:/app/enterprise
      - ../community:/app/community
      - ../tutorials:/app/tutorials
      - ../venv:/app/venv
      - ../.odoorc:/app/.odoorc
      # where odoo stores its session data
      - ./volumes/.odoo-share:/root/.local/share/Odoo/

  setup:
    build:
      context: .
      dockerfile: ./Dockerfile.setup
    volumes:
      - ../enterprise:/app/enterprise
      - ../community:/app/community
      - ../tutorials:/app/tutorials
      - ../venv:/app/venv
      - ~/.ssh:/root/.ssh:ro
