#!/usr/bin/env python3

# script made by thha

# this script does the same as odoo-bin, but it overrides the logger behavior
# to always show some info values (e.g.: installed modules, test results, etc.)
# so that we can set a higher log_level (e.g.: warn) without losing crucial info

import logging


origin_logger_get_logger = logging.getLogger
origin_logger_set_level = logging.Logger.setLevel
origin_logger_init = logging.Logger.__init__

LEVELS = ('INFO', 'WARNING', 'ERROR', 'CRITICAL')
LEVEL_BY_NAME = {name: getattr(logging, name, logging.INFO) for name in LEVELS}

"""
    PATCH PURPOSE
    -------------

    - If `--log-level` is specified, it will display all the logs which level is higher or equal to the specified minimum log level, plus the important logs
    - If `--log-level` is not specified, it will keep pooping all the logs

    For each newly created logger:
        If the logger level (the level threshold below which logs aren't displayed) is higher than `logging.INFO`, then the level of the logger is set back to the `logging.INFO`
        Then we attach a `PleaseShowImportantLogsDearGodooFilter` to this logger, and this filter will only keep the logs with a higher or equal level to the original logger level (stored in `min_log_level`), OR the "important logs"

    Note: if the filter `min_log_level` is 0, this filter will iterate through the loggers hierarchy until it finds a logger with a non zero `min_log_level` filter and use this threshold instead (see `PleaseShowImportantLogsDearGodooFilter.filter`).

    If you want it to display other logs, feel free to toy with the `PleaseShowImportantLogsDearGodooFilter.filter` method.

    WARNING: this patch may break depending on the logging library version (standard python library only tested in 3.12)
"""

IMPORTANT_RECORD_NAME = ('odoo.service.server', 'odoo.tests.stats', 'odoo.tests.result', 'odoo', 'odoo.service.server.ThreadedServer')


class PleaseShowImportantLogsDearGodooFilter(logging.Filter):
    def __init__(self, min_log_level, logger):
        super().__init__()
        self.min_log_level = min_log_level
        self.logger = logger

    def filter(self, record):
        filter = self
        while not filter.min_log_level and filter.logger.parent:
            filter = filter.logger.parent.please_filter
        min_log_level = filter.min_log_level
        return (
            record.levelname not in LEVEL_BY_NAME
            or LEVEL_BY_NAME[record.levelname] >= min_log_level
            or record.name in IMPORTANT_RECORD_NAME
        )

# This root logger is created by default when loading the logging library, we have to give him the custom filter like the other future loggers !
root_logger = logging.getLogger('root')
root_logger.please_filter = PleaseShowImportantLogsDearGodooFilter(root_logger.level, root_logger)
root_logger.addFilter(root_logger.please_filter)

INFO_LEVEL = getattr(logging, 'INFO', logging.INFO)


# Setting the logger level should also update the level of the related filter
def my_set_level(self: logging.Logger, level):
    self.please_filter.min_log_level = level
    origin_logger_set_level(self, min(INFO_LEVEL, level))


def my_logger_init(self: logging.Logger, name, level=logging.NOTSET):
    origin_logger_init(self, name, level)
    self.please_filter = PleaseShowImportantLogsDearGodooFilter(level, self)
    self.addFilter(self.please_filter)
    origin_logger_set_level(self, min(level, INFO_LEVEL))


logging.Logger.setLevel = my_set_level
logging.Logger.__init__ = my_logger_init


# original odoo-bin
import odoo.cli

if __name__ == "__main__":
    odoo.cli.main()
