#!/usr/bin/env python3

# script made by thha

# this script does the same as odoo-bin, but it overrides the logger behavior
# to always show some info values (e.g.: installed modules, test results, etc.)
# so that we can set a higher log_level (e.g.: warn) without losing crucial info

import logging

origin_logger_get_logger = logging.getLogger
origin_logger_set_level = logging.Logger.setLevel
origin_logger_init = logging.Logger.__init__

LEVELS = ('INFO', 'WARNING', 'ERROR', 'CRITICAL')
LEVEL_BY_NAME = {name: getattr(logging, name, logging.INFO) for name in LEVELS}


class PleaseShowImportantLogsDearGodoo(logging.Filter):
    def __init__(self, min_log_level, logger):
        super().__init__()
        self.min_log_level = min_log_level
        self.logger = logger

    def filter(self, record):
        filter = self
        while not filter.min_log_level and filter.logger.parent:
            filter = filter.logger.parent.please_filter
        min_log_level = filter.min_log_level
        return ((record.levelname not in LEVEL_BY_NAME or LEVEL_BY_NAME[record.levelname] >= min_log_level)
            or record.name in ('odoo.service.server', 'odoo.tests.stats', 'odoo.tests.result')
            or (record.name == 'odoo.modules.loading' and record.msg.find('modules loaded in') != -1)
            or (record.name == 'odoo.modules.loading' and record.msg.find('Loading module') != -1))


info_level = getattr(logging, 'INFO', logging.INFO)


def my_set_level(self: logging.Logger, level):
    please_filters = list(filter(lambda filter: isinstance(filter, PleaseShowImportantLogsDearGodoo), self.filters))
    if not please_filters:
        if self.name in ('', 'root'):
            self.please_filter = PleaseShowImportantLogsDearGodoo(level, self)
            self.addFilter(self.please_filter)
        else:
            raise RuntimeError('Could not find any custom filter, is there a problem with the init of the logger ?')
    if len(please_filters) > 1:
        raise RuntimeError('Found way too many filters !')
    if please_filters:
        please_filters[0].min_log_level = level
    origin_logger_set_level(self, min(info_level, level))


def my_logger_init(self: logging.Logger, name, level=logging.NOTSET):
    origin_logger_init(self, name, level)
    self.please_filter = PleaseShowImportantLogsDearGodoo(level, self)
    self.addFilter(self.please_filter)
    origin_logger_set_level(self, min(level, info_level))


logging.Logger.setLevel = my_set_level
logging.Logger.__init__ = my_logger_init

import odoo.cli

# original odoo-bin
if __name__ == "__main__":
    odoo.cli.main()
